// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 11.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace AppliedSystems.Tam.Ui.Tests
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.IO;
    using System.Text.RegularExpressions;
    using System.Windows.Input;

    using AppliedSystems.Tam.Ui.Tests.BaseUIElements;
    using AppliedSystems.Tam.Ui.Tests.Params;
    using AppliedSystems.Tam.Ui.Tests.UIElements;

    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    
    public partial class UIMap
    {
        
        #region Properties
        public UITheAgencyManagerSignWindow UITheAgencyManagerSignWindow
        {
            get
            {
                if ((this.mUITheAgencyManagerSignWindow == null))
                {
                    this.mUITheAgencyManagerSignWindow = new UITheAgencyManagerSignWindow();
                }
                return this.mUITheAgencyManagerSignWindow;
            }
        }

        public UIPedalCyclesWindow UIPedalCyclesWindow
        {
            get
            {
                if ((this.mUIPedalCyclesWindow == null))
                {
                    this.mUIPedalCyclesWindow = new UIPedalCyclesWindow();
                }
                return this.mUIPedalCyclesWindow;
            }
        }

        public UIPolicyAttachmentsWindow UIPolicyAttachmentsWindow
        {
            get
            {
                if ((this.mUIPolicyAttachmentsWindow == null))
                {
                    this.mUIPolicyAttachmentsWindow = new UIPolicyAttachmentsWindow();
                }
                return this.mUIPolicyAttachmentsWindow;
            }
        }

        public UIAttachmentDetailWindow UIAttachmentDetailWindow
        {
            get
            {
                if ((this.mUIAttachmentDetailWindow == null))
                {
                    this.mUIAttachmentDetailWindow = new UIAttachmentDetailWindow();
                }
                return this.mUIAttachmentDetailWindow;
            }
        }

        public UIAttatchmentsMenuWindow UIAttachmentsMenuWindow
        {
            get
            {
                if ((this.mUIAttatchmentsMenuWindow == null))
                {
                    this.mUIAttatchmentsMenuWindow = new UIAttatchmentsMenuWindow();
                }
                return this.mUIAttatchmentsMenuWindow;
            }
        }

        public UITheAgencyManagerWindow1 UITheAgencyManagerWindow1
        {
            get
            {
                if ((this.mUITheAgencyManagerWindow1 == null))
                {
                    this.mUITheAgencyManagerWindow1 = new UITheAgencyManagerWindow1();
                }
                return this.mUITheAgencyManagerWindow1;
            }
        }
        
        public UICustomertxt1TdsfsWindow UICustomertxt1tdsfsWindow
        {
            get
            {
                if ((this.mUICustomertxt1tdsfsWindow == null))
                {
                    this.mUICustomertxt1tdsfsWindow = new UICustomertxt1TdsfsWindow();
                }
                return this.mUICustomertxt1tdsfsWindow;
            }
        }
        
        public UIAssignClientNumberWindow UIAssignClientNumberWindow
        {
            get
            {
                return new UIAssignClientNumberWindow();
     
            }
        }
        
        public UIVerifyWindow UIVerifyWindow
        {
            get
            {
                if ((this.mUIVerifyWindow == null))
                {
                    this.mUIVerifyWindow = new UIVerifyWindow();
                }
                return this.mUIVerifyWindow;
            }
        }
        
        public UISelectaPolicyNumberWindow UISelectaPolicyNumberWindow
        {
            get
            {
                if ((this.mUISelectaPolicyNumberWindow == null))
                {
                    this.mUISelectaPolicyNumberWindow = new UISelectaPolicyNumberWindow();
                }
                return this.mUISelectaPolicyNumberWindow;
            }
        }
        
        public UICurrentOrFutureWindow UICurrentOrFutureWindow
        {
            get
            {
                if ((this.mUICurrentOrFutureWindow == null))
                {
                    this.mUICurrentOrFutureWindow = new UICurrentOrFutureWindow();
                }
                return this.mUICurrentOrFutureWindow;
            }
        }
        
        public UIProposerTypeWindow UIProposerTypeWindow
        {
            get
            {
                if ((this.mUIProposerTypeWindow == null))
                {
                    this.mUIProposerTypeWindow = new UIProposerTypeWindow();
                }
                return this.mUIProposerTypeWindow;
            }
        }
        
        public UIProposerDetailsWindow UIProposerDetailsWindow
        {
            get
            {
                if ((this.mUIProposerDetailsWindow == null))
                {
                    this.mUIProposerDetailsWindow = new UIProposerDetailsWindow();
                }
                return this.mUIProposerDetailsWindow;
            }
        }
        
        public UISearchResultForB338TWindow UISearchResultForB338TWindow
        {
            get
            {
                if ((this.mUISearchResultForB338TWindow == null))
                {
                    this.mUISearchResultForB338TWindow = new UISearchResultForB338TWindow();
                }
                return this.mUISearchResultForB338TWindow;
            }
        }
        
        public UIDriverDetailsWindow UIDriverDetailsWindow
        {
            get
            {
                if ((this.mUIDriverDetailsWindow == null))
                {
                    this.mUIDriverDetailsWindow = new UIDriverDetailsWindow();
                }
                return this.mUIDriverDetailsWindow;
            }
        }
        
        public UIVehicleLookupWindow UIVehicleLookupWindow
        {
            get
            {
                if ((this.mUIVehicleLookupWindow == null))
                {
                    this.mUIVehicleLookupWindow = new UIVehicleLookupWindow();
                }
                return this.mUIVehicleLookupWindow;
            }
        }
        
        public UIInsurEtamWindow UIInsurEtamWindow
        {
            get
            {
                if ((this.mUIInsurEtamWindow == null))
                {
                    this.mUIInsurEtamWindow = new UIInsurEtamWindow();
                }
                return this.mUIInsurEtamWindow;
            }
        }

        public UIPersonalLinesDialogWindow UIPersonalLinesDialogWindow
        {
            get
            {
                if ((this.mUIPersonalLinesDialogWindow == null))
                {
                    this.mUIPersonalLinesDialogWindow = new UIPersonalLinesDialogWindow();
                }
                return this.mUIPersonalLinesDialogWindow;
            }
        }

        public UIPersonalLinesWindow UIPersonalLinesWindow
        {
            get
            {
                if ((this.mUIPersonalLinesWindow == null))
                {
                    this.mUIPersonalLinesWindow = new UIPersonalLinesWindow();
                }
                return this.mUIPersonalLinesWindow;
            }
        }

        public UISecondApplicantDetaiWindow UISecondApplicantDetaiWindow
        {
            get
            {
                if ((this.mUISecondApplicantDetaiWindow == null))
                {
                    this.mUISecondApplicantDetaiWindow = new UISecondApplicantDetaiWindow();
                }
                return this.mUISecondApplicantDetaiWindow;
            }
        }

        public UISpecifiedItemsInsideWindow UISpecifiedItemsInsideWindow
        {
            get
            {
                if ((this.mUISpecifiedItemsInsideWindow == null))
                {
                    this.mUISpecifiedItemsInsideWindow = new UISpecifiedItemsInsideWindow();
                }
                return this.mUISpecifiedItemsInsideWindow;
            }
        }
        
        public UICreditCheckWindow UICreditCheckWindow
        {
            get
            {
                if ((this.mUICreditCheckWindow == null))
                {
                    this.mUICreditCheckWindow = new UICreditCheckWindow();
                }
                return this.mUICreditCheckWindow;
            }
        }
        
        public UIQuoteResultsWindow UIQuoteResultsWindow
        {
            get
            {
                if ((this.mUIQuoteResultsWindow == null))
                {
                    this.mUIQuoteResultsWindow = new UIQuoteResultsWindow();
                }
                return this.mUIQuoteResultsWindow;
            }
        }
        
        public UIInsurEtamWindow1 UIInsurEtamWindow1
        {
            get
            {
                if ((this.mUIInsurEtamWindow1 == null))
                {
                    this.mUIInsurEtamWindow1 = new UIInsurEtamWindow1();
                }
                return this.mUIInsurEtamWindow1;
            }
        }
        
        public UIPaymentMethodsWindow UIPaymentMethodsWindow
        {
            get
            {
                if ((this.mUIPaymentMethodsWindow == null))
                {
                    this.mUIPaymentMethodsWindow = new UIPaymentMethodsWindow();
                }
                return this.mUIPaymentMethodsWindow;
            }
        }
        
        public UIConfirmDocumentsWindow UIConfirmDocumentsWindow
        {
            get
            {
                if ((this.mUIConfirmDocumentsWindow == null))
                {
                    this.mUIConfirmDocumentsWindow = new UIConfirmDocumentsWindow();
                }
                return this.mUIConfirmDocumentsWindow;
            }
        }
        
        public UIPolicyDateTimeWindow UIPolicyDateTimeWindow
        {
            get
            {
                if ((this.mUIPolicyDateTimeWindow == null))
                {
                    this.mUIPolicyDateTimeWindow = new UIPolicyDateTimeWindow();
                }
                return this.mUIPolicyDateTimeWindow;
            }
        }
        
        public UISavethefileasWindow UISavethefileasWindow
        {
            get
            {
                if ((this.mUISavethefileasWindow == null))
                {
                    this.mUISavethefileasWindow = new UISavethefileasWindow();
                }
                return this.mUISavethefileasWindow;
            }
        }
        
        public UIPointOfSaleWindow UIPointOfSaleWindow
        {
            get
            {
                if ((this.mUIPointOfSaleWindow == null))
                {
                    this.mUIPointOfSaleWindow = new UIPointOfSaleWindow();
                }
                return this.mUIPointOfSaleWindow;
            }
        }
        
        public UIImporttoTAMWindow UIImporttoTAMWindow
        {
            get
            {
                if ((this.mUIImporttoTAMWindow == null))
                {
                    this.mUIImporttoTAMWindow = new UIImporttoTAMWindow();
                }
                return this.mUIImporttoTAMWindow;
            }
        }
        
        public UITransactiontoinsertWindow UITransactiontoinsertWindow
        {
            get
            {
                if ((this.mUITransactiontoinsertWindow == null))
                {
                    this.mUITransactiontoinsertWindow = new UITransactiontoinsertWindow();
                }
                return this.mUITransactiontoinsertWindow;
            }
        }

        public UITamxml7Window UITamxml7Window
        {
            get
            {
                if ((this.mUITamxml7Window == null))
                {
                    this.mUITamxml7Window = new UITamxml7Window();
                }
                return this.mUITamxml7Window;
            }
        }
        
        public UIPolicyrtyertWindow UIPolicyrtyertWindow
        {
            get
            {
                if ((this.mUIPolicyrtyertWindow == null))
                {
                    this.mUIPolicyrtyertWindow = new UIPolicyrtyertWindow();
                }
                return this.mUIPolicyrtyertWindow;
            }
        }
        
        public UISelectTaminsurerforiWindow UISelectTaminsurerforiWindow
        {
            get
            {
                if ((this.mUISelectTaminsurerforiWindow == null))
                {
                    this.mUISelectTaminsurerforiWindow = new UISelectTaminsurerforiWindow();
                }
                return this.mUISelectTaminsurerforiWindow;
            }
        }
        
        public UIPolicyautotestWindow UIPolicyautotestWindow
        {
            get
            {
                if ((this.mUIPolicyautotestWindow == null))
                {
                    this.mUIPolicyautotestWindow = new UIPolicyautotestWindow();
                }
                return this.mUIPolicyautotestWindow;
            }
        }

        public UITransactionListWindow1 UITransactionListWindow
        {
            get
            {
                if ((this.mUITransactionListWindow == null))
                {
                    this.mUITransactionListWindow = new UITransactionListWindow1();
                }
                return this.mUITransactionListWindow;
            }
        }
        
        
        public UIViewQuoteDetailsWindow UIViewQuoteDetailsWindow
        {
            get
            {
                if ((this.mUIViewQuoteDetailsWindow == null))
                {
                    this.mUIViewQuoteDetailsWindow = new UIViewQuoteDetailsWindow();
                }
                return this.mUIViewQuoteDetailsWindow;
            }
        }
        
        public UIDemandsNeedsMotorComWindow UIDemandsNeedsMotorComWindow
        {
            get
            {
                if ((this.mUIDemandsNeedsMotorComWindow == null))
                {
                    this.mUIDemandsNeedsMotorComWindow = new UIDemandsNeedsMotorComWindow();
                }
                return this.mUIDemandsNeedsMotorComWindow;
            }
        }

        public UIQuotesResultsWindow UIQuotesResultsWindow
        {
            get
            {
                if ((this.mUIQuotesResultsWindow == null))
                {
                    this.mUIQuotesResultsWindow = new UIQuotesResultsWindow();
                }
                return this.mUIQuotesResultsWindow;
            }
        }
        
        public UIBrokerAddonsWindow UIBrokerAddonsWindow
        {
            get
            {
                if ((this.mUIBrokerAddonsWindow == null))
                {
                    this.mUIBrokerAddonsWindow = new UIBrokerAddonsWindow();
                }
                return this.mUIBrokerAddonsWindow;
            }
        }
        
        public UIPolicyDetailConfirmationWindow UIPolicyDetailConfirmationWindow
        {
            get
            {
                if ((this.mUIPolicyDetailConfirmationWindow == null))
                {
                    this.mUIPolicyDetailConfirmationWindow = new UIPolicyDetailConfirmationWindow();
                }
                return this.mUIPolicyDetailConfirmationWindow;
            }
        }
        
        public UIAcceptWithAnotherProWindow UIAcceptWithAnotherProWindow
        {
            get
            {
                if ((this.mUIAcceptWithAnotherProWindow == null))
                {
                    this.mUIAcceptWithAnotherProWindow = new UIAcceptWithAnotherProWindow();
                }
                return this.mUIAcceptWithAnotherProWindow;
            }
        }
        
        public UIQuoteSelectListWindow UIQuoteSelectListWindow
        {
            get
            {
                if ((this.mUIQuoteSelectListWindow == null))
                {
                    this.mUIQuoteSelectListWindow = new UIQuoteSelectListWindow();
                }
                return this.mUIQuoteSelectListWindow;
            }
        }

        public UIOverridePremiumWindow UIOverridePremiumWindow
        {
            get
            {
                if ((this.mUIOverridePremiumWindow == null))
                {
                    this.mUIOverridePremiumWindow = new UIOverridePremiumWindow();
                }
                return this.mUIOverridePremiumWindow;
            }
        }
        
        public UIWhichpolicywouldyoulWindow UIWhichpolicywouldyoulWindow
        {
            get
            {
                if ((this.mUIWhichpolicywouldyoulWindow == null))
                {
                    this.mUIWhichpolicywouldyoulWindow = new UIWhichpolicywouldyoulWindow();
                }
                return this.mUIWhichpolicywouldyoulWindow;
            }
        }
        
        public UIProductSelectionWindow UIProductSelectionWindow
        {
            get
            {
                if ((this.mUIProductSelectionWindow == null))
                {
                    this.mUIProductSelectionWindow = new UIProductSelectionWindow();
                }
                return this.mUIProductSelectionWindow;
            }
        }

        public UIPleaseSelectWhoToFolWindow UIPleaseSelectWhoToFolWindow
        {
            get
            {
                if ((this.mUIPleaseSelectWhoToFolWindow == null))
                {
                    this.mUIPleaseSelectWhoToFolWindow = new UIPleaseSelectWhoToFolWindow();
                }
                return this.mUIPleaseSelectWhoToFolWindow;
            }
        }
        
        public UIMidTermAdjustmentsWindow UIMidTermAdjustmentsWindow
        {
            get
            {
                if ((this.mUIMidTermAdjustmentsWindow == null))
                {
                    this.mUIMidTermAdjustmentsWindow = new UIMidTermAdjustmentsWindow();
                }
                return this.mUIMidTermAdjustmentsWindow;
            }
        }
        
        public UIMTAEffectiveDatesWindow UIMTAEffectiveDatesWindow
        {
            get
            {
                if ((this.mUIMTAEffectiveDatesWindow == null))
                {
                    this.mUIMTAEffectiveDatesWindow = new UIMTAEffectiveDatesWindow();
                }
                return this.mUIMTAEffectiveDatesWindow;
            }
        }
        
        public UIPolicygdfhdfdfghgdfWindow UIPolicygdfhdfdfghgdfWindow
        {
            get
            {
                if ((this.mUIPolicygdfhdfdfghgdfWindow == null))
                {
                    this.mUIPolicygdfhdfdfghgdfWindow = new UIPolicygdfhdfdfghgdfWindow();
                }
                return this.mUIPolicygdfhdfdfghgdfWindow;
            }
        }
        
        public UIConfirmMTAWindow UIConfirmMTAWindow
        {
            get
            {
                if ((this.mUIConfirmMTAWindow == null))
                {
                    this.mUIConfirmMTAWindow = new UIConfirmMTAWindow();
                }
                return this.mUIConfirmMTAWindow;
            }
        }
        
        public UIClaimsWindow UIClaimsWindow
        {
            get
            {
                if ((this.mUIClaimsWindow == null))
                {
                    this.mUIClaimsWindow = new UIClaimsWindow();
                }
                return this.mUIClaimsWindow;
            }
        }
        
        public UIOpenWindow UIOpenWindow
        {
            get
            {
                if ((this.mUIOpenWindow == null))
                {
                    this.mUIOpenWindow = new UIOpenWindow();
                }
                return this.mUIOpenWindow;
            }
        }
        
        public UIBlankPageMicrosoftInWindow UIBlankPageMicrosoftInWindow
        {
            get
            {
                if ((this.mUIBlankPageMicrosoftInWindow == null))
                {
                    this.mUIBlankPageMicrosoftInWindow = new UIBlankPageMicrosoftInWindow();
                }
                return this.mUIBlankPageMicrosoftInWindow;
            }
        }
        
        public UIWindowsSecurityWindow UIWindowsSecurityWindow
        {
            get
            {
                if ((this.mUIWindowsSecurityWindow == null))
                {
                    this.mUIWindowsSecurityWindow = new UIWindowsSecurityWindow();
                }
                return this.mUIWindowsSecurityWindow;
            }
        }
        
        public UIInsurEcomSystemMaintWindow UIInsurEcomSystemMaintWindow
        {
            get
            {
                if ((this.mUIInsurEcomSystemMaintWindow == null))
                {
                    this.mUIInsurEcomSystemMaintWindow = new UIInsurEcomSystemMaintWindow();
                }
                return this.mUIInsurEcomSystemMaintWindow;
            }
        }
        
        public UISearchResultForBN16BWindow UISearchResultForBN16BWindow
        {
            get
            {
                if ((this.mUISearchResultForBN16BWindow == null))
                {
                    this.mUISearchResultForBN16BWindow = new UISearchResultForBN16BWindow();
                }
                return this.mUISearchResultForBN16BWindow;
            }
        }
        
        public UIRegressIETamPolicyWindow UIRegressIETamPolicyWindow
        {
            get
            {
                if ((this.mUIRegressIETamPolicyWindow == null))
                {
                    this.mUIRegressIETamPolicyWindow = new UIRegressIETamPolicyWindow();
                }
                return this.mUIRegressIETamPolicyWindow;
            }
        }
        
        public UIRenewalLoaderWindow UIRenewalLoaderWindow
        {
            get
            {
                if ((this.mUIRenewalLoaderWindow == null))
                {
                    this.mUIRenewalLoaderWindow = new UIRenewalLoaderWindow();
                }
                return this.mUIRenewalLoaderWindow;
            }
        }
        
        public UIIETAMRenewalsWindow UIIETAMRenewalsWindow
        {
            get
            {
                if ((this.mUIIETAMRenewalsWindow == null))
                {
                    this.mUIIETAMRenewalsWindow = new UIIETAMRenewalsWindow();
                }
                return this.mUIIETAMRenewalsWindow;
            }
        }
        
        public UIPoliciesAutoRenewedAWindow UIPoliciesAutoRenewedAWindow
        {
            get
            {
                if ((this.mUIPoliciesAutoRenewedAWindow == null))
                {
                    this.mUIPoliciesAutoRenewedAWindow = new UIPoliciesAutoRenewedAWindow();
                }
                return this.mUIPoliciesAutoRenewedAWindow;
            }
        }
        
        public UIRenewalSearchWindow UIRenewalSearchWindow
        {
            get
            {
                if ((this.mUIRenewalSearchWindow == null))
                {
                    this.mUIRenewalSearchWindow = new UIRenewalSearchWindow();
                }
                return this.mUIRenewalSearchWindow;
            }
        }
        
        public UIFilterRenewalRecordsWindow UIFilterRenewalRecordsWindow
        {
            get
            {
                if ((this.mUIFilterRenewalRecordsWindow == null))
                {
                    this.mUIFilterRenewalRecordsWindow = new UIFilterRenewalRecordsWindow();
                }
                return this.mUIFilterRenewalRecordsWindow;
            }
        }
        
        public UIAUTO1871001Window UIAUTO1871001Window
        {
            get
            {
                if ((this.mUIAUTO1871001Window == null))
                {
                    this.mUIAUTO1871001Window = new UIAUTO1871001Window();
                }
                return this.mUIAUTO1871001Window;
            }
        }
        
        public UIPrintDocumentsWindow UIPrintDocumentsWindow
        {
            get
            {
                if ((this.mUIPrintDocumentsWindow == null))
                {
                    this.mUIPrintDocumentsWindow = new UIPrintDocumentsWindow();
                }
                return this.mUIPrintDocumentsWindow;
            }
        }
        
        public UIConfirmWindow UIConfirmWindow
        {
            get
            {
                if ((this.mUIConfirmWindow == null))
                {
                    this.mUIConfirmWindow = new UIConfirmWindow();
                }
                return this.mUIConfirmWindow;
            }
        }
        
        public UIMTASuccessfulWindow UIMTASuccessfulWindow
        {
            get
            {
                if ((this.mUIMTASuccessfulWindow == null))
                {
                    this.mUIMTASuccessfulWindow = new UIMTASuccessfulWindow();
                }
                return this.mUIMTASuccessfulWindow;
            }
        }
        
        public UIRebrokeResultsScreenWindow UIRebrokeResultsScreenWindow
        {
            get
            {
                if ((this.mUIRebrokeResultsScreenWindow == null))
                {
                    this.mUIRebrokeResultsScreenWindow = new UIRebrokeResultsScreenWindow();
                }
                return this.mUIRebrokeResultsScreenWindow;
            }
        }
        
        public Uiautoxxx1000Window Uiautoxxx1000Window
        {
            get
            {
                if ((this.mUiautoxxx1000Window == null))
                {
                    this.mUiautoxxx1000Window = new Uiautoxxx1000Window();
                }
                return this.mUiautoxxx1000Window;
            }
        }
        
        public UIAmendRiskWindow UIAmendRiskWindow
        {
            get
            {
                if ((this.mUIAmendRiskWindow == null))
                {
                    this.mUIAmendRiskWindow = new UIAmendRiskWindow();
                }
                return this.mUIAmendRiskWindow;
            }
        }
        
        public UIAmendRiskResultsWindow UIAmendRiskResultsWindow
        {
            get
            {
                if ((this.mUIAmendRiskResultsWindow == null))
                {
                    this.mUIAmendRiskResultsWindow = new UIAmendRiskResultsWindow();
                }
                return this.mUIAmendRiskResultsWindow;
            }
        }
        
        public UIAUTO2211001Window UIAUTO2211001Window
        {
            get
            {
                if ((this.mUIAUTO2211001Window == null))
                {
                    this.mUIAUTO2211001Window = new UIAUTO2211001Window();
                }
                return this.mUIAUTO2211001Window;
            }
        }
        
        public UIRenewalAcceptWindow UIRenewalAcceptWindow
        {
            get
            {
                if ((this.mUIRenewalAcceptWindow == null))
                {
                    this.mUIRenewalAcceptWindow = new UIRenewalAcceptWindow();
                }
                return this.mUIRenewalAcceptWindow;
            }
        }
        
        public UIInsurerNoticeRevaluaWindow UIInsurerNoticeRevaluaWindow
        {
            get
            {
                if ((this.mUIInsurerNoticeRevaluaWindow == null))
                {
                    this.mUIInsurerNoticeRevaluaWindow = new UIInsurerNoticeRevaluaWindow();
                }
                return this.mUIInsurerNoticeRevaluaWindow;
            }
        }
        
        public UIRenewalsNewBusinessAWindow UIRenewalsNewBusinessAWindow
        {
            get
            {
                if ((this.mUIRenewalsNewBusinessAWindow == null))
                {
                    this.mUIRenewalsNewBusinessAWindow = new UIRenewalsNewBusinessAWindow();
                }
                return this.mUIRenewalsNewBusinessAWindow;
            }
        }
        
        public UIAUTO2251001Window UIAUTO2251001Window
        {
            get
            {
                if ((this.mUIAUTO2251001Window == null))
                {
                    this.mUIAUTO2251001Window = new UIAUTO2251001Window();
                }
                return this.mUIAUTO2251001Window;
            }
        }
        
        public UIHouseholdRenewalsWindow UIHouseholdRenewalsWindow
        {
            get
            {
                if ((this.mUIHouseholdRenewalsWindow == null))
                {
                    this.mUIHouseholdRenewalsWindow = new UIHouseholdRenewalsWindow();
                }
                return this.mUIHouseholdRenewalsWindow;
            }
        }

        public UIHouseholdRenewalsResultsWindow UIHouseholdRenewalsResultsWindow
        {
            get
            {
                if ((this.mUIHouseholdRenewalsResultsWindow == null))
                {
                    this.mUIHouseholdRenewalsResultsWindow = new UIHouseholdRenewalsResultsWindow();
                }
                return this.mUIHouseholdRenewalsResultsWindow;
            }
        }
        
        public UICreditCheckAtRenewalWindow UICreditCheckAtRenewalWindow
        {
            get
            {
                if ((this.mUICreditCheckAtRenewalWindow == null))
                {
                    this.mUICreditCheckAtRenewalWindow = new UICreditCheckAtRenewalWindow();
                }
                return this.mUICreditCheckAtRenewalWindow;
            }
        }

        public UiautoWindow UIAUTOWindow
        {
            get
            {
                if ((this.mUiautoWindow == null))
                {
                    this.mUiautoWindow = new UiautoWindow();
                }
                return this.mUiautoWindow;
            }
        }
        
        public UIHouseholdRebrokeResuWindow UIHouseholdRebrokeResuWindow
        {
            get
            {
                if ((this.mUIHouseholdRebrokeResuWindow == null))
                {
                    this.mUIHouseholdRebrokeResuWindow = new UIHouseholdRebrokeResuWindow();
                }
                return this.mUIHouseholdRebrokeResuWindow;
            }
        }
        
        public UIAUTO2311001Window UIAUTO2311001Window
        {
            get
            {
                if ((this.mUIAUTO2311001Window == null))
                {
                    this.mUIAUTO2311001Window = new UIAUTO2311001Window();
                }
                return this.mUIAUTO2311001Window;
            }
        }
        
        public UIRenewalsNewBusinessAWindow1 UIRenewalsNewBusinessAWindow1
        {
            get
            {
                if ((this.mUIRenewalsNewBusinessAWindow1 == null))
                {
                    this.mUIRenewalsNewBusinessAWindow1 = new UIRenewalsNewBusinessAWindow1();
                }
                return this.mUIRenewalsNewBusinessAWindow1;
            }
        }
        
        public UIWindowsSecurityWindow1 UIWindowsSecurityWindow1
        {
            get
            {
                if ((this.mUIWindowsSecurityWindow1 == null))
                {
                    this.mUIWindowsSecurityWindow1 = new UIWindowsSecurityWindow1();
                }
                return this.mUIWindowsSecurityWindow1;
            }
        }
        
        public UIWarningWindow UIWarningWindow
        {
            get
            {
                if ((this.mUIWarningWindow == null))
                {
                    this.mUIWarningWindow = new UIWarningWindow();
                }
                return this.mUIWarningWindow;
            }
        }
        
        public UIErrorWindow UIErrorWindow
        {
            get
            {
                if ((this.mUIErrorWindow == null))
                {
                    this.mUIErrorWindow = new UIErrorWindow();
                }
                return this.mUIErrorWindow;
            }
        }


        public UISelectTamActivityTypWindow UISelectTamActivityTypWindow
        {
            get
            {
                if ((this.mUISelectTamActivityTypWindow == null))
                {
                    this.mUISelectTamActivityTypWindow = new UISelectTamActivityTypWindow();
                }
                return this.mUISelectTamActivityTypWindow;
            }
        }

        public UIPleaseSelectWhoToFolWindow UIPleaseselectWHOtofolWindow
        {
            get
            {
                if ((this.mUIPleaseselectWHOtofolWindow == null))
                {
                    this.mUIPleaseselectWHOtofolWindow = new UIPleaseSelectWhoToFolWindow();
                }
                return this.mUIPleaseselectWHOtofolWindow;
            }
        }

        public TopWindow TopWindow
        {
            get
            {
                if ((this.mTopWindow == null))
                {
                    this.mTopWindow = new TopWindow();
                }
                return this.mTopWindow;
            }
        }

        public UIViewAttachmentWindow UIViewAttachmentWindow
        {
            get
            {
                if ((this.mUIViewAttachmentWindow == null))
                {
                    this.mUIViewAttachmentWindow = new UIViewAttachmentWindow();
                }
                return this.mUIViewAttachmentWindow;
            }
        }

        public UIOpenwithWindow UIOpenwithWindow
        {
            get
            {
                if ((this.mUIOpenwithWindow == null))
                {
                    this.mUIOpenwithWindow = new UIOpenwithWindow();
                }
                return this.mUIOpenwithWindow;
            }
        }

        public UIIEPolicyDocumentWindow UIIEPolicyDocumentWindow
        {
            get
            {
                return new UIIEPolicyDocumentWindow();
            }
        }

        public UIItemPdfSecureWindow UIItemPdfSecureWindow
        {
            get
            {
                if ((this.mUIItemPdfSecureWindow == null))
                {
                    this.mUIItemPdfSecureWindow = new UIItemPdfSecureWindow();
                }
                return this.mUIItemPdfSecureWindow;
            }
        }

        public UIDocumentPropertiesWindow UIDocumentPropertiesWindow
        {
            get
            {
                if ((this.mUIDocumentPropertiesWindow == null))
                {
                    this.mUIDocumentPropertiesWindow = new UIDocumentPropertiesWindow();
                }
                return this.mUIDocumentPropertiesWindow;
            }
        }

        public UIDemand2DocMicrosoftWWindow UIDemand2docMicrosoftWWindow
        {
            get
            {
                if ((this.mUIDemand2docMicrosoftWWindow == null))
                {
                    this.mUIDemand2docMicrosoftWWindow = new UIDemand2DocMicrosoftWWindow();
                }
                return this.mUIDemand2docMicrosoftWWindow;
            }
        }

        public UIFindandGotoWindow UIFindandGotoWindow
        {
            get
            {
                if ((this.mUIFindandGotoWindow == null))
                {
                    this.mUIFindandGotoWindow = new UIFindandGotoWindow();
                }
                return this.mUIFindandGotoWindow;
            }
        }

        public UIMicrosoftOfficeWordVWindow UIMicrosoftOfficeWordVWindow
        {
            get
            {
                if ((this.mUIMicrosoftOfficeWordVWindow == null))
                {
                    this.mUIMicrosoftOfficeWordVWindow = new UIMicrosoftOfficeWordVWindow();
                }
                return this.mUIMicrosoftOfficeWordVWindow;
            }
        }

        public UIUpdateGeneralTransacWindow UIUpdateGeneralTransacWindow
        {
            get
            {
                if ((this.mUIUpdateGeneralTransacWindow == null))
                {
                    this.mUIUpdateGeneralTransacWindow = new UIUpdateGeneralTransacWindow();
                }
                return this.mUIUpdateGeneralTransacWindow;
            }
        }

        public UICommissionAdjustmentWindow UICommissionAdjustmentWindow
        {
            get
            {
                if ((this.mUICommissionAdjustmentWindow == null))
                {
                    this.mUICommissionAdjustmentWindow = new UICommissionAdjustmentWindow();
                }
                return this.mUICommissionAdjustmentWindow;
            }
        }

        public UIPolicyWindow UIPolicyWindow
        {
            get
            {
                if ((this.mUIPolicyWindow == null))
                {
                    this.mUIPolicyWindow = new UIPolicyWindow();
                }
                return this.mUIPolicyWindow;
            }
        }
        #endregion
        
        #region Fields

        private UIPersonalLinesDialogWindow mUIPersonalLinesDialogWindow;

        private UICommissionAdjustmentWindow mUICommissionAdjustmentWindow;

        private UIUpdateGeneralTransacWindow mUIUpdateGeneralTransacWindow;

        private UITransactionListWindow1 mUITransactionListWindow;

        private UIDemand2DocMicrosoftWWindow mUIDemand2docMicrosoftWWindow;

        private UIFindandGotoWindow mUIFindandGotoWindow;

        private UIMicrosoftOfficeWordVWindow mUIMicrosoftOfficeWordVWindow;

        private UIItemPdfSecureWindow mUIItemPdfSecureWindow;

        private UIDocumentPropertiesWindow mUIDocumentPropertiesWindow;

  
        private UITheAgencyManagerSignWindow mUITheAgencyManagerSignWindow;
        
        private UITheAgencyManagerWindow1 mUITheAgencyManagerWindow1;
        
        private UICustomertxt1TdsfsWindow mUICustomertxt1tdsfsWindow;
               
        private UIVerifyWindow mUIVerifyWindow;
        
        private UISelectaPolicyNumberWindow mUISelectaPolicyNumberWindow;
        
        private UICurrentOrFutureWindow mUICurrentOrFutureWindow;
        
        private UIProposerTypeWindow mUIProposerTypeWindow;
        
        private UIProposerDetailsWindow mUIProposerDetailsWindow;
        
        private UISearchResultForB338TWindow mUISearchResultForB338TWindow;
        
        private UIDriverDetailsWindow mUIDriverDetailsWindow;
        
        private UIVehicleLookupWindow mUIVehicleLookupWindow;
        
        private UIInsurEtamWindow mUIInsurEtamWindow;

        private UIPersonalLinesWindow mUIPersonalLinesWindow;

        private UISecondApplicantDetaiWindow mUISecondApplicantDetaiWindow;

        private UISpecifiedItemsInsideWindow mUISpecifiedItemsInsideWindow;
        
        private UICreditCheckWindow mUICreditCheckWindow;
        
        private UIQuoteResultsWindow mUIQuoteResultsWindow;
        
        private UIInsurEtamWindow1 mUIInsurEtamWindow1;
        
        private UIPaymentMethodsWindow mUIPaymentMethodsWindow;
        
        private UIConfirmDocumentsWindow mUIConfirmDocumentsWindow;
        
        private UIPolicyDateTimeWindow mUIPolicyDateTimeWindow;
        
        private UISavethefileasWindow mUISavethefileasWindow;
        
        private UIPointOfSaleWindow mUIPointOfSaleWindow;
        
        private UIImporttoTAMWindow mUIImporttoTAMWindow;
        
        private UITransactiontoinsertWindow mUITransactiontoinsertWindow;

        private UITamxml7Window mUITamxml7Window;
        
        private UIPolicyrtyertWindow mUIPolicyrtyertWindow;
        
        private UISelectTaminsurerforiWindow mUISelectTaminsurerforiWindow;
        
        private UIPolicyautotestWindow mUIPolicyautotestWindow;
        
        private UIViewQuoteDetailsWindow mUIViewQuoteDetailsWindow;
        
        private UIDemandsNeedsMotorComWindow mUIDemandsNeedsMotorComWindow;
        
        private UIQuotesResultsWindow mUIQuotesResultsWindow;
        
        private UIBrokerAddonsWindow mUIBrokerAddonsWindow;
        
        private UIPolicyDetailConfirmationWindow mUIPolicyDetailConfirmationWindow;
        
        private UIAcceptWithAnotherProWindow mUIAcceptWithAnotherProWindow;
        
        private UIQuoteSelectListWindow mUIQuoteSelectListWindow;
        
        private UIOverridePremiumWindow mUIOverridePremiumWindow;
        
        private UIWhichpolicywouldyoulWindow mUIWhichpolicywouldyoulWindow;
        
        private UIProductSelectionWindow mUIProductSelectionWindow;
               
        private UIPleaseSelectWhoToFolWindow mUIPleaseSelectWhoToFolWindow;
        
        private UIMidTermAdjustmentsWindow mUIMidTermAdjustmentsWindow;
        
        private UIMTAEffectiveDatesWindow mUIMTAEffectiveDatesWindow;
        
        private UIPolicygdfhdfdfghgdfWindow mUIPolicygdfhdfdfghgdfWindow;
        
        private UIConfirmMTAWindow mUIConfirmMTAWindow;
        
        private UIClaimsWindow mUIClaimsWindow;
        
        private UIOpenWindow mUIOpenWindow;
        
        private UIBlankPageMicrosoftInWindow mUIBlankPageMicrosoftInWindow;
        
        private UIWindowsSecurityWindow mUIWindowsSecurityWindow;
        
        private UIInsurEcomSystemMaintWindow mUIInsurEcomSystemMaintWindow;
        
        private UISearchResultForBN16BWindow mUISearchResultForBN16BWindow;
        
        private UIRegressIETamPolicyWindow mUIRegressIETamPolicyWindow;
        
        private UIRenewalLoaderWindow mUIRenewalLoaderWindow;
        
        private UIIETAMRenewalsWindow mUIIETAMRenewalsWindow;
        
        private UIPoliciesAutoRenewedAWindow mUIPoliciesAutoRenewedAWindow;
        
        private UIRenewalSearchWindow mUIRenewalSearchWindow;
        
        private UIFilterRenewalRecordsWindow mUIFilterRenewalRecordsWindow;
        
        private UIAUTO1871001Window mUIAUTO1871001Window;
        
        private UIPrintDocumentsWindow mUIPrintDocumentsWindow;
        
        private UIConfirmWindow mUIConfirmWindow;
        
        private UIMTASuccessfulWindow mUIMTASuccessfulWindow;
        
        private UIRebrokeResultsScreenWindow mUIRebrokeResultsScreenWindow;
        
        private Uiautoxxx1000Window mUiautoxxx1000Window;
        
        private UIAmendRiskWindow mUIAmendRiskWindow;
        
        private UIAmendRiskResultsWindow mUIAmendRiskResultsWindow;
        
        private UIAUTO2211001Window mUIAUTO2211001Window;
        
        private UIRenewalAcceptWindow mUIRenewalAcceptWindow;
        
        private UIInsurerNoticeRevaluaWindow mUIInsurerNoticeRevaluaWindow;
        
        private UIRenewalsNewBusinessAWindow mUIRenewalsNewBusinessAWindow;
        
        private UIAUTO2251001Window mUIAUTO2251001Window;
        
        private UIHouseholdRenewalsWindow mUIHouseholdRenewalsWindow;
        
        private UICreditCheckAtRenewalWindow mUICreditCheckAtRenewalWindow;
        
        private UiautoWindow mUiautoWindow;
        
        private UIHouseholdRebrokeResuWindow mUIHouseholdRebrokeResuWindow;
        
        private UIAUTO2311001Window mUIAUTO2311001Window;
        
        private UIRenewalsNewBusinessAWindow1 mUIRenewalsNewBusinessAWindow1;
        
        private UIWindowsSecurityWindow1 mUIWindowsSecurityWindow1;
        
        private UIWarningWindow mUIWarningWindow;
        
        private UIErrorWindow mUIErrorWindow;

        private UIPedalCyclesWindow mUIPedalCyclesWindow;

        private SelectTamInsurersAndActivityParams mSelectTamInsurersAndActivityParams;

        private UISelectTamActivityTypWindow mUISelectTamActivityTypWindow;

        private UIPleaseSelectWhoToFolWindow mUIPleaseselectWHOtofolWindow;

        private TopWindow mTopWindow;

        private UIHouseholdRenewalsResultsWindow mUIHouseholdRenewalsResultsWindow;

        private UIPolicyAttachmentsWindow mUIPolicyAttachmentsWindow;

        private UIViewAttachmentWindow mUIViewAttachmentWindow;

        private UIOpenwithWindow mUIOpenwithWindow;

        private UIAttatchmentsMenuWindow mUIAttatchmentsMenuWindow;

        private UIAttachmentDetailWindow mUIAttachmentDetailWindow;

        private UIPolicyWindow mUIPolicyWindow;
        #endregion
    }
}
